var users = [
	{
		name: 'Thai Hoang Nguyen',
		email: 'thaihoang.nguyen@acomsolutions.com',
		password: 'rivaldo',
		id: 'thaihoang.nguyen@acomsolutions.com',
		categories: ['category_bank_account'],
		testsuites: [],
		type: 'user'
	},
	{
		name: 'Thien Vo',
		email: 'thien.vo@acomsolutions.com',
		password: 'rivaldo',
		type: 'user',
		id: 'thien.vo@acomsolutions.com',
		testsuites: [],
		categories: ['category_payment']
	},
]

var categories = [
	{
		name: 'Bank Account',
		description: 'Bank Account Category',
		user: 'thaihoang.nguyen@acomsolutions.com',
		id: 'category_bank_account',
		type: 'category',
		testsuites: ['testsuite_pending', 'testsuite_approval'],
		status: 'pass',
		work_items: [15149, 15150]
	},
	{
		name: 'Payment',
		description: 'Payment Category',
		user: 'thien.vo@acomsolutions.com',
		id: 'category_payment',
		type: 'category',
		testsuites: ['testsuite_notification', 'testsuite_ach'],
		status: 'fail',
		work_items: [15151]
	}
]

var testsuites = [
	{
		name: 'Pending',
		description: 'testsuite Pending',
		user: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_pending',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_pending', 'testgroup_primary_pending'],
		testcases: ['testcase_pending_1', 'testcase_pending_2'],
		category: 'category_payment',
		work_items: [15152, 15153]
	},
	{
		name: 'Approval',
		description: 'testsuite Aproval',
		user: 'thien.vo@acomsolutions.com',
		id: 'testsuite_approval',
		type: 'testsuite',		
		testgroups: ['testgroup_preconfig_approval', 'testgroup_primary_approval'],
		testcases: ['testcase_approval_1', 'testcase_approval_2'],
		category: 'category_payment',
		work_items: [15154, 15155]
	},
	{
		name: 'Notification',
		description: 'testsuite Notification',
		user: 'thaihoang.nguyen@acomsolutions.com',
		id: 'testsuite_notification',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_notification', 'testgroup_primary_notification'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15156, 15157]
	},
	{
		name: 'ACH',
		description: 'testsuite ACH',
		user: 'thien.vo@acomsolutions.com',
		id: 'testsuite_ach',
		type: 'testsuite',
		testgroups: ['testgroup_preconfig_ach', 'testgroup_primary_ach'],
		testcases: [],
		category: 'category_bank_account',
		work_items: [15158, 15159]
		
	}
]

var testgroups = [
	{
		name: 'Group Preconfig Pending',
		description: 'testgroup Preconfig Pending',
		id: 'testgroup_preconfig_pending',
		testcases: ['testcase_preconfig_pending_1', 'testcase_preconfig_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15160, 15161]
	},
	{
		id: 'testgroup_primary_pending',
		name: 'Group Primary Pending',
		description: 'testgroup Primary Pending',
		testcases: ['testcase_primary_pending_1', 'testcase_primary_pending_2'],
		testsuite: 'testsuite_pending',
		work_items: [15162, 15163]
	},
	{
		id: 'testgroup_preconfig_approval',
		name: 'Group Preconfig Approval',
		description: 'testgroup Preconfig Aproval',
		testcases: ['testcase_preconfig_approval_1', 'testcase_preconfig_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15164, 15165]
	},
	{
		id: 'testgroup_primary_approval',
		name: 'Group Primary Approval',
		description: 'testgroup Primary Aproval',
		testcases: ['testcase_primary_approval_1', 'testcase_primary_approval_2'],
		testsuite: 'testsuite_approval',
		work_items: [15166, 15167]
	},
	{
		id: 'testgroup_preconfig_notification',
		name: 'Group Preconfig Notification',
		description: 'testgroup Preconfig Notification',
		testcases: ['testcase_preconfig_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15168, 15169]
	},
	{
		id: 'testgroup_primary_notification',
		name: 'Group Primary Notification',
		description: 'testgroup Primary Notification',
		testcases: ['testcase_primary_notification_1'],
		testsuite: 'testsuite_notification',
		work_items: [15170, 15171]
	},
	{
		id: 'testgroup_preconfig_ach',
		name: 'Group Preconfig ACH',
		description: 'testgroup Preconfig ACH',
		testcases: ['testcase_preconfig_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15172, 15173]
	},
	{
		id: 'testgroup_primary_ach',
		name: 'Group Primary ACH',
		description: 'testgroup Primary ACH',
		testcases: ['testcase_primary_ach_1'],
		testsuite: 'testsuite_ach',
		work_items: [15174, 15175]
	}
]

var testcases = [
	{
		id: 'testcase_pending_1',
		name: 'Testcase Pending 1',
		description: 'testcase Pending 1',
		type: 'testcase',
		keywords: [],
		testsuite: 'testsuite_pending',
		work_items: [15176],
		enabled: true,
		primary: true,
		dependency: '',
	},
	{
		id: 'testcase_pending_2',
		name: 'Testcase Pending 2',
		description: 'testcase Pending 2',
		type: 'testcase',
		keywords: [],
		testsuite: 'testsuite_pending',
		work_items: [15177],
		enabled: true,
		primary: false,
		dependency: 'testcase_pending_1',
	},
	{
		id: 'testcase_approval_1',
		name: 'Testcase Aproval 1',
		description: 'testcase Aproval 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15178],
		enabled: true,
		primary: false,
		dependency: 'testcase_pending_1',
	},
	{
		id: 'testcase_approval_2',
		name: 'Testcase Aproval 2',
		description: 'testcase Aproval 2',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15179],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_1',
		name: 'Testcase Preconfig Pending 1',
		description: 'testcase Preconfig Pending 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15180],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_pending_2',
		name: 'Testcase Preconfig Pending 2',
		description: 'testcase Preconfig Pending 2',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_pending',
		testsuite: '',
		work_items: [15181],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_1',
		name: 'Testcase Primary Pending1',
		description: 'testcase Primary Pending 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15182],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_pending_2',
		name: 'Testcase Primary Pending2',
		description: 'testcase Primary Pending 2',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_pending',
		testsuite: '',
		work_items: [15183],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_1',
		name: 'Testcase Preconfig Approval 1',
		description: 'testcase Preconfig Aproval 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15184],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_approval_2',
		name: 'Testcase Preconfig Approval 2',
		description: 'testcase Preconfig Aproval 2',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_approval',
		testsuite: '',
		work_items: [15185],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_1',
		name: 'Testcase Primary Approval 1',
		description: 'testcase Primary Aproval 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15186],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_approval_2',
		name: 'Testcase Primary Approval 2',
		description: 'testcase Primary Aproval 2',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_approval',
		testsuite: '',
		work_items: [15187],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_notification_1',
		name: 'Testcase Preconfig Notification 1',
		description: 'testcase Preconfig Notification ',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15188],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_notification_1',
		name: 'Testcase Primary Notification 1',
		description: 'testcase Primary Notification 1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_notification',
		testsuite: '',
		work_items: [15189],
		enabled: true,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_preconfig_ach_1',
		name: 'Testcase Preconfig ACH1',
		description: 'testcase Preconfig ACH1',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_preconfig_ach',
		testsuite: '',
		work_items: [15190],
		tickable: false,
		enabled: false,
		primary: false,
		dependency: '',
	},
	{
		id: 'testcase_primary_ach_1',
		name: 'Testcase Primary ACH 1',
		description: 'testcase Primary ACH ',
		type: 'testcase',
		keywords: [],
		testgroup: 'testgroup_primary_ach',
		testsuite: '',
		work_items: [15191],
		enabled: true,
		primary: false,
		dependency: '',
	}
]

export default { 
	users,
	categories,
	testsuites,
	testgroups,
	testcases
}